'use client';
import PhoneInput from './phone-input';
import {useState} from 'react';
import {FileText,Phone,LockKeyhole,ArrowRight,Eye,EyeOff} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
export default function Login(){
 const [mode,setMode]=useState('login'),[phone,setPhone]=useState(''),[pin,setPin]=useState(''),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[show,setShow]=useState(false);
 return <main className="login-page"><div className="login-brand"><FileText size={32}/><strong>SÙNG TUYẾN</strong><span>BÁO GIÁ VẬT LIỆU XÂY DỰNG</span></div><section className="login-card"><h1>Báo giá nhanh,<br/>gọn trong một ảnh.</h1><p>Bảng giá và báo giá riêng của bạn, dùng trên điện thoại và máy tính.</p><Tabs value={mode} onValueChange={v=>{setMode(v);setError('');}}><TabsList className="login-tabs"><TabsTrigger value="login">Đăng nhập</TabsTrigger><TabsTrigger value="register">Tạo tài khoản</TabsTrigger></TabsList></Tabs><form onSubmit={async e=>{e.preventDefault();if(busy)return;setError('');setBusy(true);try{const r=await fetch('/api/account',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:mode,phone,pin,confirmPin:confirm})});const j=await r.json() as {error?:string};if(!r.ok)throw new Error(j.error||'Chưa đăng nhập được.');window.location.replace('/');}catch(e){setError((e as Error).message);setBusy(false);}}}><fieldset disabled={busy}><label className="field"><span><Phone size={15}/>Số điện thoại</span><PhoneInput autoComplete="username" required value={phone} onValueChange={setPhone} placeholder="0964 023 003"/></label><label className="field"><span><LockKeyhole size={15}/>Mật khẩu 3 số</span><div className="pin-field"><input type={show?'text':'password'} inputMode="numeric" autoComplete={mode==='register'?'new-password':'current-password'} pattern="[0-9]{3}" minLength={3} maxLength={3} required value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,''))} placeholder="•••"/><button type="button" aria-label={show?'Ẩn mật khẩu':'Hiện mật khẩu'} onClick={()=>setShow(!show)}>{show?<EyeOff/>:<Eye/>}</button></div></label>{mode==='register'&&<label className="field"><span>Nhập lại mật khẩu</span><input type={show?'text':'password'} autoComplete="new-password" inputMode="numeric" pattern="[0-9]{3}" maxLength={3} required value={confirm} onChange={e=>setConfirm(e.target.value.replace(/\D/g,''))} placeholder="•••"/></label>}{error&&<p className="login-error" role="alert">{error}</p>}<button type="submit" className="primary login-submit">{busy?'Đang xử lý…':mode==='login'?'Đăng nhập':'Tạo tài khoản'}<ArrowRight/></button></fieldset></form><p className="login-foot">Số điện thoại là tên đăng nhập. Không gửi mã SMS.</p></section></main>;
}
